projectVersion=1.0.0-SNAPSHOT
projectGroupId=io.micronaut.scala
projectGroup=io.micronaut.scala
projectDesc=Micronaut Scala compiler plugin and integration tests
title=Micronaut Scala
githubSlug=micronaut-projects/micronaut-scala
projectUrl=https://micronaut.io
developers=Graeme Rocher

micronaut-build-version=8.0.1

org.gradle.jvmargs=-Xmx4g
org.gradle.parallel=true
org.gradle.caching=true
kotlin.stdlib.default.dependency=false
