/*
 * Copyright 2017-2026 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.scala.processing.test;

import dotty.tools.dotc.Main;
import dotty.tools.dotc.reporting.Diagnostic;
import dotty.tools.dotc.reporting.Reporter;
import dotty.tools.dotc.util.SourcePosition;
import io.micronaut.aop.internal.InterceptorRegistryBean;
import io.micronaut.context.ApplicationContext;
import io.micronaut.context.BeanDefinitionsProvider;
import io.micronaut.context.DefaultBeanDefinitionsProvider;
import io.micronaut.context.event.ApplicationEventPublisherFactory;
import io.micronaut.core.beans.BeanIntrospection;
import io.micronaut.core.naming.NameUtils;
import io.micronaut.inject.BeanDefinition;
import io.micronaut.inject.BeanDefinitionReference;
import io.micronaut.inject.ast.ClassElement;
import io.micronaut.inject.provider.BeanProviderDefinition;
import io.micronaut.inject.provider.JakartaProviderBeanDefinition;
import io.micronaut.inject.writer.BeanDefinitionWriter;
import org.jspecify.annotations.Nullable;

import java.io.File;
import java.io.IOException;
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLClassLoader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.function.Consumer;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import scala.jdk.javaapi.CollectionConverters;

/**
 * Scala compiler helper for inline test sources.
 */
public final class ScalaCompiler {

    /**
     * The default {@code -release} level. Overridable by passing an explicit {@code -release:N}
     * compiler option, so a test can pin generated bytecode to an older baseline.
     */
    private static final int DEFAULT_RELEASE = 25;

    private static final List<Path> TEMP_DIRECTORIES = new CopyOnWriteArrayList<>();

    static {
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            for (Path directory : TEMP_DIRECTORIES) {
                deleteRecursively(directory);
            }
        }, "micronaut-scala-test-cleanup"));
    }

    private ScalaCompiler() {
    }

    /**
     * Builds a classloader for a Scala source.
     *
     * @param className The primary class name
     * @param source The source
     * @return The classloader
     */
    public static URLClassLoader buildClassLoader(String className, String source) {
        return compile(className, source, classElement -> {
        }).classLoader();
    }

    /**
     * Builds a class element for the given source.
     *
     * @param className The class name
     * @param source The source
     * @return The class element
     */
    public static @Nullable ClassElement buildClassElement(String className, String source) {
        return buildClassElement(className, source, List.of());
    }

    /**
     * Builds a class element for the given source.
     *
     * @param className The class name
     * @param source The source
     * @param compilerOptions The additional compiler options
     * @return The class element
     */
    public static @Nullable ClassElement buildClassElement(String className, String source, List<String> compilerOptions) {
        List<ClassElement> elements = new ArrayList<>();
        compile(className, source, compilerOptions, elements::add);
        return elements.stream().filter(element -> element.getName().equals(className)).findFirst().orElse(null);
    }

    /**
     * Builds a bean introspection for the given source.
     *
     * @param className The class name
     * @param source The source
     * @return The introspection
     */
    public static @Nullable BeanIntrospection<?> buildBeanIntrospection(String className, String source) {
        return buildBeanIntrospection(className, source, List.of());
    }

    /**
     * Builds a bean introspection for the given source.
     *
     * @param className The class name
     * @param source The source
     * @param compilerOptions The additional compiler options
     * @return The introspection
     */
    public static @Nullable BeanIntrospection<?> buildBeanIntrospection(String className, String source, List<String> compilerOptions) {
        URLClassLoader classLoader = compile(className, source, compilerOptions, classElement -> {
        }).classLoader();
        String beanDefName = "$" + NameUtils.getSimpleName(className) + "$Introspection";
        String packageName = NameUtils.getPackageName(className);
        String introspectionName = packageName + "." + beanDefName;
        try {
            return (BeanIntrospection<?>) classLoader.loadClass(introspectionName).getDeclaredConstructor().newInstance();
        } catch (ClassNotFoundException e) {
            // No introspection was generated for this class, which is a legitimate assertion target.
            return null;
        } catch (InstantiationException | IllegalAccessException | InvocationTargetException | NoSuchMethodException e) {
            // The introspection *was* generated but could not be instantiated. Collapsing this into
            // null would hide a broken generated class behind a later NullPointerException.
            throw new IllegalStateException("Generated introspection [" + introspectionName + "] could not be instantiated", e);
        }
    }

    /**
     * Builds a bean definition for the given source.
     *
     * @param className The class name
     * @param source The source
     * @return The bean definition
     */
    public static @Nullable BeanDefinition<?> buildBeanDefinition(String className, String source) {
        return buildBeanDefinition(className, source, List.of());
    }

    /**
     * Builds a bean definition for the given source.
     *
     * @param className The class name
     * @param source The source
     * @param compilerOptions The additional compiler options
     * @return The bean definition
     */
    public static @Nullable BeanDefinition<?> buildBeanDefinition(String className, String source, List<String> compilerOptions) {
        URLClassLoader classLoader = compile(className, source, compilerOptions, classElement -> {
        }).classLoader();
        return (BeanDefinition<?>) loadDefinition(classLoader, generatedDefinitionName(className));
    }

    /**
     * Builds a bean definition whose generated class name does not follow the
     * {@code $<Class>$Definition} convention, such as an intercepted or factory-produced
     * definition.
     *
     * @param packageName The package of the generated definition
     * @param generatedClassName The simple name of the generated definition class
     * @param source The source
     * @return The bean definition
     */
    public static @Nullable BeanDefinition<?> buildBeanDefinition(String packageName, String generatedClassName, String source) {
        URLClassLoader classLoader = compile("test.Source", source, List.of(), classElement -> {
        }).classLoader();
        return (BeanDefinition<?>) loadDefinition(classLoader, packageName + "." + generatedClassName);
    }

    private static String generatedDefinitionName(String className) {
        String simpleName = NameUtils.getSimpleName(className);
        String beanDefName = (simpleName.startsWith("$") ? "" : "$") + simpleName + BeanDefinitionWriter.CLASS_SUFFIX;
        return NameUtils.getPackageName(className) + "." + beanDefName;
    }

    /**
     * Builds a bean definition reference for the given source.
     *
     * @param className The class name
     * @param source The source
     * @return The bean definition reference
     */
    public static @Nullable BeanDefinitionReference<?> buildBeanDefinitionReference(String className, String source) {
        URLClassLoader classLoader = buildClassLoader(className, source);
        return (BeanDefinitionReference<?>) loadDefinition(classLoader, generatedDefinitionName(className));
    }

    /**
     * Compiles the given source and returns the compiler warnings it produced. Warnings are the
     * channel {@code VisitorContext.warn(...)} writes to, so without this a visitor warning cannot
     * be asserted at all.
     *
     * @param className The class name
     * @param source The source
     * @return The formatted warnings, as {@code file:line:column: message} where a position exists
     */
    public static List<String> buildAndGetWarnings(String className, String source) {
        return compile(className, source, List.of(), classElement -> {
        }).warnings();
    }

    /**
     * Builds an application context for the given source.
     *
     * @param source The source
     * @param includeAllBeans Whether to include all default beans
     * @return The started context
     */
    public static ApplicationContext buildContext(String source, boolean includeAllBeans) {
        return buildContext(source, includeAllBeans, Map.of());
    }

    /**
     * Builds an application context for the given source.
     *
     * @param source The source
     * @param includeAllBeans Whether to include all default beans
     * @param config The context configuration
     * @return The started context
     */
    public static ApplicationContext buildContext(String source, boolean includeAllBeans, Map<String, Object> config) {
        return buildContext(source, includeAllBeans, config, List.of());
    }

    /**
     * Builds an application context for the given source.
     *
     * @param source The source
     * @param includeAllBeans Whether to include all default beans
     * @param config The context configuration
     * @param compilerOptions The additional compiler options
     * @return The started context
     */
    public static ApplicationContext buildContext(String source, boolean includeAllBeans, Map<String, Object> config, List<String> compilerOptions) {
        Compilation compilation = compile("test.Source", source, compilerOptions, classElement -> {
        });
        URLClassLoader classLoader = compilation.classLoader();
        return ApplicationContext.builder()
            .classLoader(classLoader)
            .environments("test")
            .properties(config)
            .beanDefinitionsProvider(new BeanDefinitionsProvider() {
                @Override
                public List<BeanDefinitionReference<?>> provide(ClassLoader ignored) {
                    List<BeanDefinitionReference<?>> references = new ArrayList<>();
                    for (String beanDefinitionName : beanDefinitionNames(compilation.outputDirectory())) {
                        // Deliberately not tolerant: a generated definition that cannot be loaded is
                        // a plugin defect, and swallowing it here surfaces later as a confusing
                        // NoSuchBeanException, or not at all.
                        BeanDefinitionReference<?> reference = (BeanDefinitionReference<?>) loadDefinition(classLoader, beanDefinitionName);
                        if (reference != null) {
                            references.add(reference);
                        }
                    }
                    if (includeAllBeans) {
                        references.addAll(new DefaultBeanDefinitionsProvider().provide(classLoader));
                    } else {
                        references.add(new InterceptorRegistryBean());
                        references.add(new BeanProviderDefinition());
                        references.add(new JakartaProviderBeanDefinition());
                        references.add(new ApplicationEventPublisherFactory<>());
                    }
                    return references;
                }
            })
            .start();
    }

    /**
     * Compiles the source and returns every diagnostic the compiler produced, without
     * failing on errors. A diagnostic's position is the point of this: an error reported
     * against an element the visitor named should carry that element's file, line and
     * column, not {@code NoSourcePosition}.
     *
     * @param className The class name
     * @param source The source
     * @return The warnings and errors, as {@code file:line:column: message} where a
     *     position exists
     */
    public static Diagnostics buildAndGetDiagnostics(String className, String source) {
        try {
            Path workDirectory = Files.createTempDirectory("micronaut-scala-test");
            registerForCleanup(workDirectory);
            Path sourceDirectory = Files.createDirectories(workDirectory.resolve("src"));
            Path outputDirectory = Files.createDirectories(workDirectory.resolve("classes"));
            Path sourceFile = sourceDirectory.resolve(NameUtils.getSimpleName(className) + ".scala");
            Files.writeString(sourceFile, source, StandardCharsets.UTF_8);
            return runCompiler(outputDirectory, List.of(sourceFile), List.of(), false);
        } catch (IOException e) {
            throw new IllegalStateException(e);
        }
    }

    static Compilation compile(String className, String source, Consumer<ClassElement> classElementConsumer) {
        return compile(className, source, List.of(), classElementConsumer);
    }

    static Compilation compile(String className, String source, List<String> compilerOptions, Consumer<ClassElement> classElementConsumer) {
        return compile(List.of(SourceFile.scala(className, source)), compilerOptions, classElementConsumer);
    }

    /**
     * Compiles one or more Scala sources in a single compiler run. Compiling several sources
     * together is the only way to exercise separate compilation within one run, which is where
     * symbol-completion and phase-ordering problems in the plugin show up.
     *
     * @param sources The sources
     * @param compilerOptions The additional compiler options
     * @param classElementConsumer Receives every visited class element
     * @return The compilation
     */
    static Compilation compile(List<SourceFile> sources, List<String> compilerOptions, Consumer<ClassElement> classElementConsumer) {
        return compile(sources, compilerOptions, List.of(), classElementConsumer);
    }

    /**
     * Compiles sources in one compiler run against the output of earlier runs.
     *
     * <p>This is the shape of an incremental build: the classes the sources refer to were
     * compiled before, so the compiler reads them from the classpath rather than from source,
     * and the plugin sees them as classpath types. Nothing else in the harness exercises that
     * path, and it is the one Gradle and sbt take on every edit that does not touch every
     * file.</p>
     *
     * @param sources The sources
     * @param compilerOptions The additional compiler options
     * @param precompiled Output directories of earlier compilations, placed ahead of the test
     *     classpath
     * @param classElementConsumer Receives every visited class element
     * @return The compilation
     */
    static Compilation compile(
        List<SourceFile> sources,
        List<String> compilerOptions,
        List<Path> precompiled,
        Consumer<ClassElement> classElementConsumer) {
        if (sources.isEmpty()) {
            throw new IllegalArgumentException("At least one source is required");
        }
        try {
            Path workDirectory = Files.createTempDirectory("micronaut-scala-test");
            registerForCleanup(workDirectory);
            Path sourceDirectory = Files.createDirectories(workDirectory.resolve("src"));
            Path outputDirectory = Files.createDirectories(workDirectory.resolve("classes"));
            List<Path> sourceFiles = new ArrayList<>();
            for (SourceFile source : sources) {
                Path sourceFile = sourceDirectory.resolve(
                    NameUtils.getSimpleName(source.className()) + source.extension()
                );
                Files.writeString(sourceFile, source.source(), StandardCharsets.UTF_8);
                sourceFiles.add(sourceFile);
            }
            List<String> warnings = new ArrayList<>();
            ScalaClassElementCaptureVisitor.withConsumer(
                classElementConsumer,
                () -> warnings.addAll(compileSources(outputDirectory, sourceFiles, compilerOptions, precompiled))
            );
            return new Compilation(outputDirectory, newClassLoader(outputDirectory, precompiled), List.copyOf(warnings));
        } catch (IOException e) {
            throw new IllegalStateException(e);
        }
    }

    private static void registerForCleanup(Path workDirectory) {
        TEMP_DIRECTORIES.add(workDirectory);
    }

    private static void deleteRecursively(Path directory) {
        try (Stream<Path> paths = Files.walk(directory)) {
            paths.sorted(Comparator.reverseOrder()).forEach(path -> {
                try {
                    Files.deleteIfExists(path);
                } catch (IOException ignored) {
                    // Best effort: a leftover temp file must never fail a build.
                }
            });
        } catch (IOException ignored) {
            // Best effort.
        }
    }

    private static List<String> compileSources(
        Path outputDirectory,
        List<Path> sourceFiles,
        List<String> compilerOptions,
        List<Path> precompiled) {
        return runCompiler(outputDirectory, sourceFiles, compilerOptions, precompiled, true).warnings();
    }

    private static Diagnostics runCompiler(
        Path outputDirectory,
        List<Path> sourceFiles,
        List<String> compilerOptions,
        boolean failOnError) {
        return runCompiler(outputDirectory, sourceFiles, compilerOptions, List.of(), failOnError);
    }

    private static Diagnostics runCompiler(
        Path outputDirectory,
        List<Path> sourceFiles,
        List<String> compilerOptions,
        List<Path> precompiled,
        boolean failOnError) {
        String classpath = System.getProperty("micronaut.scala.test.classpath");
        String pluginJar = System.getProperty("micronaut.scala.plugin.jar");
        if (classpath == null || pluginJar == null) {
            throw new IllegalStateException("Scala test classpath or plugin jar system property is missing");
        }
        List<String> arguments = new ArrayList<>();
        arguments.add("-classpath");
        arguments.add(withPrecompiled(classpath, precompiled));
        arguments.add("-d");
        arguments.add(outputDirectory.toString());
        if (compilerOptions.stream().noneMatch(option -> option.startsWith("-release"))) {
            arguments.add("-release:" + DEFAULT_RELEASE);
        }
        arguments.add("-Xplugin:" + pluginJar);
        arguments.addAll(compilerOptions);
        for (Path sourceFile : sourceFiles) {
            arguments.add(sourceFile.toString());
        }
        Reporter reporter = Main.process(arguments.toArray(String[]::new));
        Diagnostics diagnostics = new Diagnostics(
            formatDiagnostics(CollectionConverters.asJava(reporter.allWarnings())),
            formatDiagnostics(CollectionConverters.asJava(reporter.allErrors()))
        );
        if (failOnError && reporter.hasErrors()) {
            throw new IllegalStateException(errorMessage(reporter));
        }
        return diagnostics;
    }

    private static String errorMessage(Reporter reporter) {
        String diagnostics = String.join(
            System.lineSeparator(),
            formatDiagnostics(CollectionConverters.asJava(reporter.allErrors()))
        );
        if (diagnostics.isBlank()) {
            return reporter.summary();
        }
        return diagnostics + System.lineSeparator() + reporter.summary();
    }

    /**
     * Formats diagnostics as {@code file:line:column: message} where a position is available, so a
     * test can assert both the message and where it was reported. Micronaut's
     * {@code ProcessingException} carries an originating element, and the compiler plugin resolves
     * that element's source position, so losing the position here would make that untestable.
     *
     * @param diagnostics The diagnostics
     * @return The formatted diagnostics
     */
    private static List<String> formatDiagnostics(List<? extends Diagnostic> diagnostics) {
        return diagnostics.stream().map(ScalaCompiler::formatDiagnostic).collect(Collectors.toList());
    }

    private static String formatDiagnostic(Diagnostic diagnostic) {
        String message = diagnostic.message();
        SourcePosition position = diagnostic.pos();
        if (position == null || !position.exists()) {
            return message;
        }
        // dotty reports zero-based lines and columns; report them the way the compiler prints them.
        return position.source().name() + ":" + (position.line() + 1) + ":" + (position.column() + 1)
            + ": " + message;
    }

    private static String withPrecompiled(String classpath, List<Path> precompiled) {
        if (precompiled.isEmpty()) {
            return classpath;
        }
        StringBuilder joined = new StringBuilder();
        for (Path directory : precompiled) {
            joined.append(directory.toAbsolutePath()).append(File.pathSeparatorChar);
        }
        return joined.append(classpath).toString();
    }

    private static URLClassLoader newClassLoader(Path outputDirectory, List<Path> precompiled) {
        String classpath = System.getProperty("micronaut.scala.test.classpath");
        List<URL> urls = new ArrayList<>();
        try {
            urls.add(outputDirectory.toUri().toURL());
            for (Path directory : precompiled) {
                urls.add(directory.toUri().toURL());
            }
            for (String path : classpathEntries(classpath)) {
                urls.add(new File(path).toURI().toURL());
            }
            return new URLClassLoader(urls.toArray(URL[]::new), ScalaCompiler.class.getClassLoader());
        } catch (MalformedURLException e) {
            throw new IllegalStateException(e);
        }
    }

    private static List<String> classpathEntries(String classpath) {
        List<String> entries = new ArrayList<>();
        int start = 0;
        for (int i = 0; i <= classpath.length(); i++) {
            if (i == classpath.length() || classpath.charAt(i) == File.pathSeparatorChar) {
                if (i > start) {
                    entries.add(classpath.substring(start, i));
                }
                start = i + 1;
            }
        }
        return entries;
    }

    private static List<String> beanDefinitionNames(Path outputDirectory) {
        Path serviceDirectory = outputDirectory.resolve("META-INF/micronaut/io.micronaut.inject.BeanDefinitionReference");
        if (!Files.isDirectory(serviceDirectory)) {
            return List.of();
        }
        try (Stream<Path> files = Files.list(serviceDirectory)) {
            return files.filter(Files::isRegularFile).map(path -> path.getFileName().toString()).toList();
        } catch (IOException e) {
            return List.of();
        }
    }

    private static @Nullable Object loadDefinition(ClassLoader classLoader, String name) {
        Class<?> definitionClass;
        try {
            definitionClass = classLoader.loadClass(name);
        } catch (ClassNotFoundException e) {
            // Nothing was generated under this name, which callers assert on.
            return null;
        }
        try {
            Constructor<?> constructor = definitionClass.getDeclaredConstructor();
            constructor.setAccessible(true);
            return constructor.newInstance();
        } catch (NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            throw new IllegalStateException("Generated class [" + name + "] could not be instantiated", e);
        }
    }

    /**
     * The diagnostics a compilation produced.
     *
     * @param warnings The formatted warnings
     * @param errors The formatted errors
     */
    public record Diagnostics(List<String> warnings, List<String> errors) {
    }

    /**
     * Compilation result.
     *
     * @param outputDirectory The compiler output directory
     * @param classLoader The classloader
     * @param warnings The formatted compiler warnings
     */
    record Compilation(Path outputDirectory, URLClassLoader classLoader, List<String> warnings) {
    }

    /**
     * A single source to compile.
     *
     * @param className The primary class name declared by the source, used to derive the file name
     * @param source The source text
     * @param extension The file extension, {@code .scala} or {@code .java}
     */
    public record SourceFile(String className, String source, String extension) {

        /**
         * A Scala source.
         *
         * @param className The primary class name
         * @param source The source text
         * @return The source
         */
        public static SourceFile scala(String className, String source) {
            return new SourceFile(className, source, ".scala");
        }

        /**
         * A Java source, for joint Java/Scala compilation. dotty parses Java sources for their
         * signatures, so this exercises the compiler's own Java symbol reader rather than the
         * classpath reader used for pre-compiled Java classes.
         *
         * @param className The primary class name
         * @param source The source text
         * @return The source
         */
        public static SourceFile java(String className, String source) {
            return new SourceFile(className, source, ".java");
        }
    }
}
